server:
  port: 20000
  servlet:
    session:
      timeout: 30m

spring:
  application:
    name: gulimall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  thymeleaf:
    cache: false

  redis:
    host: 127.0.0.1
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true

  session:
    store-type: redis

seata:
  enabled: true
  enable-auto-data-source-proxy: true
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      namespace: d85ff827-c1c8-44e5-b3af-132a74392e27
      data-id: seataServer.Properties
      group: SEATA_GROUP
      username: nacos
      password: nacos
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      namespace: d85ff827-c1c8-44e5-b3af-132a74392e27
      username: nacos
      password: nacos

