server:
  port: 25000

spring:
  main:
    allow-circular-references: true
  application:
    name: gulimall-seckill
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8333
        port: 8719

    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 127.0.0.1
  task:
    execution:
      pool:
        core-size: 5
        max-size: 50
  session:
    store-type: redis
  rabbitmq:
    virtual-host: /
    host: 127.0.0.1
    listener:
      direct:
        acknowledge-mode: manual
  thymeleaf:
    cache: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    com.atguigu.gulimall: debug
#
feign:
  sentinel:
    enabled: true