server:
  port: 35000

spring:
  main:
    allow-circular-references: true
  application:
    name: gulimall-cart
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8333
        port: 8719

  redis:
    host: 127.0.0.1
  thymeleaf:
    cache: false
management:
  endpoints:
    web:
      exposure:
        include: '*'

seata:
  enabled: true
  enable-auto-data-source-proxy: true
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      namespace: d85ff827-c1c8-44e5-b3af-132a74392e27
      data-id: seataServer.Properties
      group: SEATA_GROUP
      username: nacos
      password: nacos
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      namespace: d85ff827-c1c8-44e5-b3af-132a74392e27
      username: nacos
      password: nacos